// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMbLSFA9JHZlF3NCO1RGoetn4TgDYhTxA',
    appId: '1:43060082396:web:db71a1bd4d59659d2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    authDomain: 'tic-tac-toe-7d956.firebaseapp.com',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbLSFA9JHZlF3NCO1RGoetn4TgDYhTxA',
    appId: '1:43060082396:android:db71a1bd4d59659d2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZmhAIsTNOz6EsbjDx3o6fcz-6GA9guY',
    appId: '1:43060082396:ios:b39d3d6c1ba55cdd2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZmhAIsTNOz6EsbjDx3o6fcz-6GA9guY',
    appId: '1:43060082396:ios:b39d3d6c1ba55cdd2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMbLSFA9JHZlF3NCO1RGoetn4TgDYhTxA',
    appId: '1:43060082396:android:db71a1bd4d59659d2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBMbLSFA9JHZlF3NCO1RGoetn4TgDYhTxA',
    appId: '1:43060082396:android:db71a1bd4d59659d2c2619',
    messagingSenderId: '43060082396',
    projectId: 'tic-tac-toe-7d956',
    storageBucket: 'tic-tac-toe-7d956.firebasestorage.app',
  );
}
